### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mahantor** [ali-0315/aparat_playlist_downloader#6]
سلام
علت این ارور چیه؟؟؟
```
PS C:\Users\SaeID\Desktop\aparat_playlist_downloader-main> python main.py
Give me a Aparat playlist id: 1224728
Give me the quality: (Examples: 144 , 240 , 360 , 480 , 720 , 1080) :480
Type "y" if you want to create a .txt file that contain all the videos link otherwise type "n" to start download now:n
Downloading Playlist مقاومت مصالح یک  ...
Traceback (most recent call last):
  File "C:\Users\SaeID\Desktop\aparat_playlist_downloader-main\main.py", line 59, in <module>
    download_video(download_url, output_path)
  File "C:\Users\SaeID\Desktop\aparat_playlist_downloader-main\main.py", line 12, in download_video
    with open(output_path, 'wb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Downloads/مقاومت مصالح یک /مقاومت مصالح یک - جلسه اول - بخش اول-480p.mp4'
```

**Comment by ali-0315** [comment]
سلام 
مشکل حل شد
